# Generated by Django 6.0 on 2026-01-04 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=30, null=True)),
                ('Stud_id', models.IntegerField(blank=True, null=True)),
                ('Department', models.CharField(blank=True, max_length=30, null=True)),
                ('Phone_Number', models.IntegerField(blank=True, null=True)),
                ('Bus_Number', models.IntegerField(blank=True, null=True)),
                ('Bus_Route', models.CharField(blank=True, max_length=30, null=True)),
                ('Stud_Profile_Pic', models.ImageField(blank=True, null=True, upload_to='Student Profile Pic')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
