# Generated by Django 6.0 on 2026-01-04 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bus_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='Stud_Profile_Pic',
            field=models.ImageField(blank=True, null=True, upload_to='student_profile_pic'),
        ),
    ]
