# Generated by Django 6.0 on 2026-01-04 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bus_App', '0002_alter_studentdata_stud_profile_pic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bus_No', models.IntegerField(blank=True, null=True)),
                ('Bus_Route', models.CharField(blank=True, null=True)),
                ('Arrival', models.TimeField(blank=True, null=True)),
                ('Departure', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaffData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=30, null=True)),
                ('Staff_id', models.IntegerField(blank=True, null=True)),
                ('Phone_Number', models.IntegerField(blank=True, null=True)),
                ('Bus_Number', models.IntegerField(blank=True, null=True)),
                ('Bus_Route', models.CharField(blank=True, max_length=30, null=True)),
                ('Staff_Profile_Pic', models.ImageField(blank=True, null=True, upload_to='staff_profile_pic')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
