# Generated by Django 6.0.1 on 2026-02-05 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bus_App', '0004_studentdata_qr_code_busentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busentry',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries_done', to='Bus_App.staffdata'),
        ),
        migrations.AlterField(
            model_name='busentry',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bus_App.studentdata'),
        ),
    ]
