# Generated by Django 6.0.1 on 2026-03-03 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bus_App', '0005_alter_busentry_staff_alter_busentry_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetINTouch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Number', models.IntegerField(null=True)),
                ('Email', models.EmailField(max_length=30)),
                ('Subject', models.CharField(max_length=30)),
                ('Message', models.TextField(null=True)),
            ],
        ),
    ]
